"use strict";
// ──────────────────────────────────────────────────────────────────────
// BeliefGuard — Post-Patch Validator Engine
// Performs a secondary heuristic analysis on the generated unified diff
// to ensure no USER_CONSTRAINT beliefs are violated before the patch
// is surfaced to the developer.
// ──────────────────────────────────────────────────────────────────────
Object.defineProperty(exports, "__esModule", { value: true });
exports.validateGeneratedPatch = validateGeneratedPatch;
// ── Negation pairs for heuristic constraint-violation detection ──────
var CONSTRAINT_NEGATION_PAIRS = [
    [/\bpreserve\b/i, /\bremov(e|ed|ing)\b|\bdelet(e|ed|ing)\b/i],
    [/\bdo not alter\b/i, /\bmodif(y|ied|ies|ying)\b/i],
    [/\bdo not change\b/i, /\bchang(e|ed|es|ing)\b/i],
    [/\bno new dependenc/i, /\bnpm install\b|\byarn add\b|\bimport .+ from\b/i],
    [/\bbackward.?compat/i, /\bbreaking change/i],
    [/\bread[- ]?only\b/i, /\bwrit(e|able|ing|ten)\b/i],
    [/\bimmutable\b/i, /\bmutabl(e|tion|ted)\b/i],
    [/\bdo not (touch|modify|remove|delete)\b/i, /\b(touch|modif|remov|delet)(ed|ing|ies|y|e|s)?\b/i],
];
/**
 * Extracts the file paths modified by a unified diff by parsing the
 * `---` and `+++` header lines.
 */
function extractModifiedFiles(diffString) {
    var files = new Set();
    var lines = diffString.split(/\r?\n/);
    for (var _i = 0, lines_1 = lines; _i < lines_1.length; _i++) {
        var line = lines_1[_i];
        // Unified diff header: +++ b/path/to/file or +++ path/to/file
        var match = line.match(/^\+\+\+\s+(?:b\/)?(.+)/);
        if (match && match[1] !== '/dev/null') {
            files.add(match[1].trim());
        }
    }
    return Array.from(files);
}
/**
 * Extracts meaningful keywords from a constraint statement for matching
 * against diff content and file paths.
 */
function extractConstraintKeywords(statement) {
    var STOP_WORDS = new Set([
        'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been',
        'do', 'does', 'did', 'not', 'must', 'should', 'will', 'can',
        'of', 'in', 'to', 'for', 'with', 'on', 'at', 'from', 'by',
        'and', 'but', 'or', 'it', 'its', 'this', 'that', 'any',
    ]);
    return statement
        .toLowerCase()
        .replace(/[^a-z0-9\s._/-]/g, ' ')
        .split(/\s+/)
        .filter(function (w) { return w.length > 2 && !STOP_WORDS.has(w); });
}
/**
 * Validates a generated unified diff against the set of validated beliefs.
 *
 * The validator performs two layers of heuristic checking:
 *
 *   1. **File-path matching** — If a USER_CONSTRAINT references specific
 *      files (by name or path fragment), and the diff modifies those files,
 *      it is flagged as a potential violation.
 *
 *   2. **Negation-pattern matching** — If a USER_CONSTRAINT contains a
 *      protective keyword (e.g., "preserve", "do not alter") and the diff
 *      content contains the opposing action keyword, the violation is flagged.
 *
 * @param diffString        The raw unified diff string generated by the LLM.
 * @param validatedBeliefs  The full set of beliefs (all types) from the session.
 * @returns                 A ValidationResult indicating pass/fail and specific violations.
 */
function validateGeneratedPatch(diffString, validatedBeliefs) {
    var violations = [];
    var modifiedFiles = extractModifiedFiles(diffString);
    var diffLower = diffString.toLowerCase();
    // Only evaluate USER_CONSTRAINT beliefs for violations
    var constraints = validatedBeliefs.filter(function (b) { return b.type === 'USER_CONSTRAINT'; });
    for (var _i = 0, constraints_1 = constraints; _i < constraints_1.length; _i++) {
        var constraint = constraints_1[_i];
        var isViolated = false;
        var keywords = extractConstraintKeywords(constraint.statement);
        // ── Check 1: File-path overlap ──────────────────────────────────
        // If the constraint mentions specific file-like tokens (containing
        // dots or slashes), check whether the diff touches those files.
        var fileTokens = keywords.filter(function (k) { return k.includes('.') || k.includes('/'); });
        for (var _a = 0, fileTokens_1 = fileTokens; _a < fileTokens_1.length; _a++) {
            var fileToken = fileTokens_1[_a];
            for (var _b = 0, modifiedFiles_1 = modifiedFiles; _b < modifiedFiles_1.length; _b++) {
                var modifiedFile = modifiedFiles_1[_b];
                if (modifiedFile.toLowerCase().includes(fileToken)) {
                    isViolated = true;
                    break;
                }
            }
            if (isViolated)
                break;
        }
        // ── Check 2: Negation-pattern conflict ──────────────────────────
        if (!isViolated) {
            for (var _c = 0, CONSTRAINT_NEGATION_PAIRS_1 = CONSTRAINT_NEGATION_PAIRS; _c < CONSTRAINT_NEGATION_PAIRS_1.length; _c++) {
                var _d = CONSTRAINT_NEGATION_PAIRS_1[_c], protectivePattern = _d[0], actionPattern = _d[1];
                if (protectivePattern.test(constraint.statement)) {
                    // The constraint is protective; check if the diff performs the action
                    if (actionPattern.test(diffString)) {
                        // Additional check: make sure the action relates to
                        // the same domain as the constraint (keyword overlap)
                        var domainOverlap = keywords.some(function (k) { return k.length > 3 && diffLower.includes(k); });
                        if (domainOverlap) {
                            isViolated = true;
                            break;
                        }
                    }
                }
            }
        }
        if (isViolated) {
            violations.push(constraint);
        }
    }
    return {
        isValid: violations.length === 0,
        violations: violations,
        diffPatch: diffString,
    };
}
